name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        # 已將標籤名稱修正為 "run"，以符合您的專案名稱
        tags: ${{ secrets.DOCKER_USERNAME }}/run:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/run:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/run:buildcache,mode=max
